data:
  input_file_name: input
  output_file_name: output
  nu: 2.5
  L: 1
  N: 128
  num_f: 30
  num_bc: 10
  num_c: 1
  num_v: 30
  method: 'descartes'
  plot: False
  save: True
  load: Falsef
  print_error: False
  print_time: True
model:
  layers:
    - 256
    - 256
    - 1
trainer:
  batch_size: 2048
  lr: 5e-4
  weight_decay: 1e-5
  lr_sch_factor: 0.7
  lr_sch_patience: 15
  lr_sch_threshold: 0.0001
  save_every: 10
  split_ratio: 0.8
  max_epochs: 10000
  stop_lr: 1e-7
  alpha: 1
  beta: 1e-3
  gamma: 1
  plot: False
  verbose: True
  print_memory: True
  force_restart: False
  seed: 42
runner:
  objective: 'all'
